#!/bin/bash

###########################################################################
# Compare the given expected times on the given dates to what is recorded #
###########################################################################

export CLIENTS="$HOME/.trackme"
export EVENT_FILE="$CLIENTS/events"
export REPORTS="$CLIENTS/reports"
export FINAL_REPORT="$REPORTS/final"

source "./utils/helpers"

compare()
{
  TARGET_CLIENT="$1"
  TARGET_PROJECT="$2"
  BILLED_TIME="$3"
  TARGET_START="$4"
  TARGET_END="$5"

  extractAndSumEntries "$(dateFormatToSeconds "$TARGET_START")" "$(dateFormatToSeconds "$TARGET_END")" "$TARGET_PROJECT"

  if [ "$(find "$REPORTS" -type f | wc -l)" -gt "0" ];then
    HOURS="$(cut -d':' -f1 <"$REPORTS/$TARGET_CLIENT/$TARGET_PROJECT")"
    MINUTES="$(cut -d':' -f2 <"$REPORTS/$TARGET_CLIENT/$TARGET_PROJECT")"
    FINAL_DURATION="$HOURS.$MINUTES"
    CURRENT_DIFF="$(bc -l <<<"$FINAL_DURATION - $EXP")"
    DIFFERENCE="$(bc -l <<<"$DIFFERENCE + $CURRENT_DIFF")"

    printf '%s->%s, Recorded time: [%s], Billed time: [%s], Diff = %s\nRunning diff = %s\n' \
      "$TARGET_START" \
      "$TARGET_END" \
      "$FINAL_DURATION" \
      "$BILLED_TIME" \
      "$CURRENT_DIFF" \
      "$DIFFERENCE" \
      >> ./DURATIONS
  else
    printf '%s\n' "No timers active for slot $TARGET_START -> $TARGET_END" >> ./DURATIONS
  fi
  rm -rf "${REPORTS:?}"/*
}

 # Main script
 if [ -z "$2" ];then
   echo "Usage: $0 <client> <project>"
   exit
 fi

DIFFERENCE=0
while read -r slot; do
  START="$(cut -d',' -f1 <<<"$slot")"
  END="$(cut -d',' -f2 <<<"$slot")"
  EXP="$(cut -d',' -f3 <<<"$slot")"
  echo "Comparing slot $START -> $END"
  compare "$1" "$2" "$EXP" "$START" "$END"
done < <(cut -d',' -f7,8,9 ~/Downloads/timeSheet.worker.list.csv)
echo "Total difference is $DIFFERENCE" >> ./DURATIONS

read -p"Remove reports? [y/N]"
if [ "$REPLY" = "y" ];then
  rm -rf ./*_DURATIONS
fi
