#!/bin/bash

###########################
# Constants used in utils #
###########################

export WD="$HOME/Git/trackMe"
export CLIENTS="trackmedata"
export EVENT_FILE="$WD/event_file"
export FINAL_EVENT_FILE="$WD/events"
export DATE_FORMAT='-R'
