#!/bin/bash

################################################################################
# Create events from the entries in FSDB, sort them and insert into event file #
################################################################################

for CLIENT in "$CLIENTS"/*; do

  if [ "$CLIENT" = "$CLIENTS/active" ] || [ "$CLIENT" = "$CLIENTS/events" ] || [ "$CLIENT" = "$CLIENTS/reports" ] ; then
    continue
  fi

  echo "Client: $CLIENT"

  for ACTIVITY in "$CLIENT"/*; do
    echo "Activity: $ACTIVITY"

    for ENTRY in "$ACTIVITY"/*; do
      COUNT=1
      while IFS= read -r line || [ -n "$line" ]; do
        case "$COUNT" in
          "1")
              START_TIME="$line"
              if ! START_TIME_SEC="$(dateFormatToSeconds "$(cut -d' ' -f1,2 --complement <<<"$START_TIME")")"; then
                echo "ERROR: start time <$START_TIME> is invalid!"
                exit
              fi
            ;;
          "2")
              END_TIME="$line"
              if ! END_TIME_SEC="$(dateFormatToSeconds "$(cut -d' ' -f1,2 --complement <<<"$END_TIME")")"; then
                echo "ERROR: end time <$END_TIME> is invalid!" exit
              fi
            ;;
          "3")
              DURATION="$(cut -d' ' -f2 <<<"$line")"
              printf '%s %s %s %s %s %s\n' \
                "$START_TIME_SEC" \
                "$END_TIME_SEC" \
                "$DURATION" \
                "${ENTRY##*/}" \
                "${ACTIVITY##*/}" \
                "${CLIENT##*/}" >> "$EVENT_FILE"
              ((COUNT = 0))
            ;;
          *)
              echo "Error, count is too high"
            ;;
        esac
        ((COUNT = COUNT + 1))
      done<"$ENTRY"
    done
  done
done

sort -n "$EVENT_FILE" > "${EVENT_FILE}-sorted"

while read -r line; do
  START_TIME="$(dateSecondsToFormat "$(cut -d' ' -f1 <<<"$line")")"
  END_TIME="$(dateSecondsToFormat "$(cut -d' ' -f2 <<<"$line")")"
  DURATION="$(cut -d' ' -f3 <<<"$line")"
  ACTIVITY="$(cut -d' ' -f4 <<<"$line")"
  PROJECT="$(cut -d' ' -f5 <<<"$line")"
  CLIENT="$(cut -d' ' -f6 <<<"$line")"

  printf '%s\n%s\n%s\n%s\n%s\n%s\n' \
    "Duration: $DURATION" \
    "Ended at $END_TIME" \
    "Started at $START_TIME" \
    "Activity: $ACTIVITY" \
    "Project: $PROJECT" \
    "Client: $CLIENT" >> "$FINAL_EVENT_FILE"

done<"${EVENT_FILE}-sorted"
