#!/bin/bash

dateSecondsToFormat()
{
  date "$DATE_FORMAT" --date="@$1"
}

dateFormatToSeconds()
{
  date --date "$1" +%s
}

diff()
{
  if [ "$1" -gt "$2" ]; then
    echo "diff would be negative, this is not allowed! Wrong order of parameters?"
    return 1
  fi

  ((DIFF = $2 - $1))
  ((SECONDS = DIFF % 60))
  ((MINUTES = (DIFF % 3600) / 60))
  ((HOURS = DIFF / 3600))

	echo "$HOURS:$MINUTES:$SECONDS"

}

showSpinner()
{
  INFO="$1"
  SPINNER_SEED="$2"
  case $((SPINNER_SEED % 8)) in
    "0")
      SPINNER="|"
      ;;
    "1")
      SPINNER="/"
      ;;
    "2")
      SPINNER="―"
      ;;
    "3")
      SPINNER="\\"
      ;;
    "4")
      SPINNER="|"
      ;;
    "5")
      SPINNER="/"
      ;;
    "6")
      SPINNER="―"
      ;;
    "7")
      SPINNER="\\"
      ;;
  esac
  printf '\r\e[0K%s  %s' "$SPINNER"   "$INFO"
}
