#!/bin/bash

pushd ~/ >/dev/null || exit

if [ -f .TRACKME_GIT_SYNC ]; then
  mv .TRACKME_GIT_SYNC .TRACKME_GIT_SYNC.NO
  echo "Not syncing with Git"
elif [ -f .TRACKME_GIT_SYNC.NO ]; then
  mv .TRACKME_GIT_SYNC.NO .TRACKME_GIT_SYNC 
  echo "Syncing with Git"
fi
