#!/bin/bash

#######################################################################
# Validate there is no overlapping evntries in temp sorted event file #
#######################################################################

source "./utils/constants"
source "./utils/helpers"

if [ ! -f "$EVENT_FILE" ];then
  echo "No event file, run create_event_file_from_DB script?"
  exit 1
fi

echo "Validating no overlapping entries..."
TOTAL=0
COUNT=0
LINES_TO_PROCESS="$(wc -l "${EVENT_FILE}-sorted" | cut -d' ' -f1)"
while read -r line; do
  if [ "$COUNT" = 0 ]; then
    echo "First row, skipping..."
    CURRENT_START_TIME_SEC="$(cut -d' ' -f1 <<<"$line")"
    CURRENT_END_TIME_SEC="$(cut -d' ' -f2 <<<"$line")"
    CURRENT_CLIENT="$(cut -d' ' -f4 <<<"$line")"
    CURRENT_PROJECT="$(cut -d' ' -f5 <<<"$line")"
    CURRENT_ACTIVITY="$(cut -d' ' -f6 <<<"$line")"
    ((COUNT += 1))
    continue
  fi

  if [ "$((COUNT % 10))" = "0" ]; then
    printf '\r\e[0K%s' "$COUNT lines processed out of $LINES_TO_PROCESS."
  fi

  PREVIOUS_START_TIME_SEC="$CURRENT_START_TIME_SEC"
  PREVIOUS_END_TIME_SEC="$CURRENT_END_TIME_SEC"
  PREVIOUS_ACTIVITY="$CURRENT_ACTIVITY"
  PREVIOUS_PROJECT="$CURRENT_PROJECT"
  PREVIOUS_CLIENT="$CURRENT_CLIENT"

  CURRENT_START_TIME_SEC="$(cut -d' ' -f1 <<<"$line")"
  CURRENT_END_TIME_SEC="$(cut -d' ' -f2 <<<"$line")"
  CURRENT_CLIENT="$(cut -d' ' -f4 <<<"$line")"
  CURRENT_PROJECT="$(cut -d' ' -f5 <<<"$line")"
  CURRENT_ACTIVITY="$(cut -d' ' -f6 <<<"$line")"

  if [ "$PREVIOUS_END_TIME_SEC" -gt "$CURRENT_START_TIME_SEC" ]; then
    ((TOTAL += 1))
    printf '\r\e[0K%s %s %s\n' \
     "Line $COUNT, at $(dateSecondsToFormat "$CURRENT_START_TIME_SEC"):" \
     "${CURRENT_ACTIVITY}@${CURRENT_PROJECT} by $CURRENT_CLIENT starts before" \
     "${PREVIOUS_ACTIVITY}@${PREVIOUS_PROJECT} by $PREVIOUS_CLIENT ends."

    if [ "$CURRENT_ACTIVITY" = "$PREVIOUS_ACTIVITY" ]; then
      printf '\r\e[0K%s\n[%s] - [%s] - [%s] - [%s] - [%s]\n[%s] - [%s] - [%s] - [%s] - [%s]\n' \
        "Activity $CURRENT_ACTIVITY is same, duplicate entry?" \
        "$(dateSecondsToFormat "$PREVIOUS_START_TIME_SEC")" "$(dateSecondsToFormat "$PREVIOUS_END_TIME_SEC")" "$PREVIOUS_ACTIVITY" "$PREVIOUS_PROJECT" "$PREVIOUS_CLIENT" \
        "$(dateSecondsToFormat "$CURRENT_START_TIME_SEC")" "$(dateSecondsToFormat "$CURRENT_END_TIME_SEC")" "$CURRENT_ACTIVITY" "$CURRENT_PROJECT" "$CURRENT_CLIENT"
    fi
  fi
  ((COUNT += 1))
done<"${EVENT_FILE}-sorted"
printf '\r\e[0K%s\n' "$COUNT lines processed out of $LINES_TO_PROCESS."
echo "Validation done, $TOTAL errors were found."
