#!/bin/bash

##########################################################
# Validate duration of events in temp sorted events file #
##########################################################

echo "Validating duration..."
while read -r line; do
  START_TIME_SEC="$(cut -d' ' -f1 <<<"$line")"
  END_TIME_SEC="$(cut -d' ' -f2 <<<"$line")"
  DURATION="$(cut -d' ' -f3 <<<"$line")"
  ACTIVITY="$(cut -d' ' -f4 <<<"$line")"
  PROJECT="$(cut -d' ' -f5 <<<"$line")"
  CLIENT="$(cut -d' ' -f6 <<<"$line")"
  REAL_DURATION="$(diff "$START_TIME_SEC" "$END_TIME_SEC")"

  if [ "$DURATION" != "$REAL_DURATION" ]; then
   echo "${ACTIVITY}@${PROJECT} by $CLIENT has invalid duration <$DURATION> - Should be $REAL_DURATION"
  fi
done<"${EVENT_FILE}-sorted"
echo "Validation done."
