#!/bin/bash

##########################################################
# Validate duration of events in temp sorted events file #
##########################################################

source "./utils/constants"
source "./utils/helpers"

echo "Validating duration..."
LINES="$(wc -l "${EVENT_FILE}-sorted" | cut -d' ' -f1)"
LINE_COUNT=0
ERRORS=0
while read -r line; do
  ((LINE_COUNT += 1))
  if [ "$((LINE_COUNT % 10))" = "0" ]; then
    printf '\r\e[0K%s' "$LINE_COUNT lines processed out of $LINES."
  fi
  START_TIME_SEC="$(cut -d' ' -f1 <<<"$line")"
  END_TIME_SEC="$(cut -d' ' -f2 <<<"$line")"
  DURATION="$(cut -d' ' -f3 <<<"$line")"
  CLIENT="$(cut -d' ' -f4 <<<"$line")"
  PROJECT="$(cut -d' ' -f5 <<<"$line")"
  ACTIVITY="$(cut -d' ' -f6 <<<"$line")"
  REAL_DURATION="$(diff "$START_TIME_SEC" "$END_TIME_SEC")"

  if [ "$DURATION" != "$REAL_DURATION" ]; then
    ((ERRORS += 1))
    echo "${ACTIVITY}@${PROJECT} by $CLIENT has invalid duration <$DURATION> - Should be $REAL_DURATION"
  fi
done<"${EVENT_FILE}-sorted"
printf '\r\e[0K%s\n' "$LINE_COUNT lines processed out of $LINES."
echo "Validation done, $ERRORS errors were found."
